import express, { Request, Response } from "express";
import multer from "multer";
const pdfParse = require("pdf-parse");

// Assuming GROQ integration is similar to what's in chat routes, else using direct fetch
const router = express.Router();
const upload = multer({ storage: multer.memoryStorage() });

const GROQ_API_KEY = process.env.GROQ_API_KEY;

router.post("/pdf-summarize", upload.single("file"), async (req: Request, res: Response): Promise<any> => {
    try {
        if (!req.file) {
            return res.status(400).json({ error: "No file uploaded" });
        }

        const mode = req.body.mode || 'detailed';

        // 1. Extract text from PDF
        const pdfData = await pdfParse(req.file.buffer);
        const textContent = pdfData.text;

        if (!textContent || textContent.trim().length === 0) {
            return res.status(400).json({ error: "Could not extract text from the PDF. It might be scanned or empty." });
        }

        // Limit text to avoid hitting token limits (approx 8000 tokens for safety, simple char slice)
        const safeTextContent = textContent.slice(0, 30000);

        // 2. Define System Prompts based on mode
        let systemPrompt = "";
        switch (mode) {
            case 'casual':
                systemPrompt = "You are a helpful assistant. Summarize the following document in a casual, easy-to-read, conversational tone. Focus only on the most interesting and broad takeaways. Assume the reader knows nothing about the topic.";
                break;
            case 'study':
                systemPrompt = "You are a strict academic tutor. Summarize the following document as a study aid. Extract key terminology, core concepts, and formulate 3-5 potential Q&A pairs that might appear on a test regarding this material.";
                break;
            case 'detailed':
            default:
                systemPrompt = "You are a professional analyst. Provide a highly detailed, comprehensive summary of the following document. Use bullet points, bolded section headers, and ensure all critical arguments and supporting data points are captured accurately.";
                break;
        }

        // 3. Call Groq
        if (!GROQ_API_KEY) {
            return res.status(500).json({ error: "Server configuration error: GROQ_API_KEY is missing." });
        }

        const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${GROQ_API_KEY}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                model: "llama-3.3-70b-versatile", // Using a robust model for summarization
                messages: [
                    { role: "system", content: systemPrompt },
                    { role: "user", content: `Please summarize the following document text:\n\n${safeTextContent}` }
                ],
                temperature: 0.5,
                max_tokens: 1500
            })
        });

        if (!response.ok) {
            const errBody = await response.text();
            console.error("Groq API Error:", errBody);
            throw new Error(`AI Provider Error: ${response.statusText}`);
        }

        const data: any = await response.json();
        const summary = data.choices[0]?.message?.content;

        if (!summary) {
            throw new Error("No summary generated by the AI.");
        }

        return res.json({ summary });

    } catch (error: any) {
        console.error("PDF Summarize Error:", error);
        return res.status(500).json({ error: error.message || "An error occurred during summarization" });
    }
});

router.post("/icon-generate", async (req: Request, res: Response): Promise<any> => {
    try {
        const { prompt } = req.body;

        if (!prompt) {
            return res.status(400).json({ error: "Prompt is required" });
        }

        const CF_ACCOUNT_ID = process.env.CF_ACCOUNT_ID;
        const CF_AI_TOKEN = process.env.CF_WORKERS_AI_TOKEN;

        if (!CF_ACCOUNT_ID || !CF_AI_TOKEN) {
            return res.status(500).json({ error: "Server configuration error: Cloudflare Workers AI credentials are missing." });
        }

        const url = `https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/ai/run/@cf/black-forest-labs/flux-1-schnell`;

        const response = await fetch(url, {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${CF_AI_TOKEN}`,
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                prompt: prompt,
                num_steps: 4
            })
        });

        if (!response.ok) {
            let errorText = "Unknown error";
            try { errorText = await response.text(); } catch (e) { }
            console.error("Cloudflare Workers AI Error:", response.status, errorText);
            throw new Error(`Image generation failed: ${response.status}`);
        }

        const contentType = response.headers.get("content-type") || "";

        if (contentType.includes("image")) {
            const arrayBuffer = await response.arrayBuffer();
            const buffer = Buffer.from(arrayBuffer);
            res.set("Content-Type", contentType);
            return res.send(buffer);
        }

        const data: any = await response.json();

        if (data.result && data.result.image) {
            const imageBuffer = Buffer.from(data.result.image, "base64");
            res.set("Content-Type", "image/png");
            return res.send(imageBuffer);
        }

        throw new Error("Unexpected response format from image generation service");

    } catch (error: any) {
        console.error("Icon Generation Error:", error);
        return res.status(500).json({ error: error.message || "An error occurred during image generation" });
    }
});

import { exec } from "child_process";
import fs from "fs";
import path from "path";
import util from "util";
import FormData from "form-data";
import fetch from "node-fetch";

const execPromise = util.promisify(exec);

router.post("/youtube-transcribe", async (req: Request, res: Response): Promise<any> => {
    try {
        const { url } = req.body;

        if (!url) {
            return res.status(400).json({ error: "YouTube URL is required" });
        }

        if (!GROQ_API_KEY) {
            return res.status(500).json({ error: "Server configuration error: GROQ_API_KEY is missing." });
        }

        // 1. Download audio using yt-dlp
        const tempId = Math.random().toString(36).substring(7);
        // Save in a temporary cross-platform location (like the OS temp dir, but for safety in the current dir temp folder)
        const tempDir = path.join(__dirname, "..", "temp");
        if (!fs.existsSync(tempDir)) {
            fs.mkdirSync(tempDir);
        }
        const outputPath = path.join(tempDir, `audio_${tempId}.mp3`);

        console.log(`Downloading audio for: ${url} to ${outputPath}`);

        // Extract worstaudio to keep size small (Whisper handles low quality fine), format to mp3, max 15 minutes
        // We add --match-filter to prevent downloading huge files if not needed, but for now just let it download
        const ytCmd = `yt-dlp -f "worstaudio" -x --audio-format mp3 -o "${outputPath}" "${url}"`;

        try {
            await execPromise(ytCmd);
        } catch (execErr: any) {
            console.error("yt-dlp error:", execErr);
            return res.status(500).json({ error: "Failed to download audio from the provided URL. Ensure it's a valid YouTube link." });
        }

        if (!fs.existsSync(outputPath)) {
            return res.status(500).json({ error: "Audio file was not created successfully." });
        }

        // 2. Send to Groq Whisper API
        console.log(`Transcribing audio: ${outputPath}`);
        const formData = new FormData();
        formData.append("file", fs.createReadStream(outputPath));
        formData.append("model", "whisper-large-v3-turbo");
        formData.append("response_format", "json");

        const response = await fetch("https://api.groq.com/openai/v1/audio/transcriptions", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${GROQ_API_KEY}`
            },
            body: formData
        });

        // 3. Cleanup temp file
        try {
            fs.unlinkSync(outputPath);
        } catch (e) {
            console.error("Failed to delete temp audio file:", e);
        }

        if (!response.ok) {
            const errBody = await response.text();
            console.error("Groq Whisper API Error:", errBody);
            throw new Error(`Transcription Failed: ${response.statusText}`);
        }

        const data = await response.json() as any;

        if (!data.text) {
            throw new Error("No transcription text returned.");
        }

        return res.json({ transcript: data.text });

    } catch (error: any) {
        console.error("Youtube Transcribe Error:", error);
        return res.status(500).json({ error: error.message || "An error occurred during transcription" });
    }
});

export default router;
